version: '3.3'
services:
  db:
    build:
      context: ../common/db/
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ../common/db/.env

